# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 12:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('direccion', models.TextField()),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('fechaNacimiento', models.DateField()),
                ('dui', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'permissions': (('ver_alumno', 'Ver alumno'),),
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('direccion', models.TextField()),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('fechaNacimiento', models.DateField()),
                ('dui', models.CharField(max_length=10)),
                ('isss', models.CharField(max_length=9)),
                ('afp', models.CharField(max_length=12)),
                ('nit', models.CharField(max_length=17)),
                ('tipo', models.CharField(choices=[('Asi', 'Asistente'), ('Pro', 'Profesor'), ('Tec', 'Tecnico')], default='Pro', max_length=3)),
                ('username', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('direccion', models.TextField()),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('fechaNacimiento', models.DateField()),
                ('dui', models.CharField(max_length=10)),
                ('username', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('alumnosInscritos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('dias_asignados', models.CharField(choices=[('Lunes y Miercoles', 'Lunes y Miercoles'), ('Martes y Jueves', 'Martes y Jueves'), ('Domingo', 'Domingo'), ('Sabado', 'Sabado'), ('Viernes', 'Viernes')], max_length=40)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cantidad_alumnos', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=8)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('trabajo', 'Trabajo'), ('movil', 'Movil')], max_length=20)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.Alumno')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.Empleado')),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.Encargado')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.Horario'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.Empleado'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.Encargado'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.Grupo'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='username',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
