# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('direccion', models.TextField()),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('fechaNacimiento', models.DateField()),
                ('dui', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('direccion', models.TextField()),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('fechaNacimiento', models.DateField()),
                ('dui', models.CharField(max_length=10)),
                ('isss', models.CharField(max_length=9)),
                ('afp', models.CharField(max_length=12)),
                ('nit', models.CharField(max_length=17)),
                ('tipo', models.CharField(choices=[('Asi', 'Asistente'), ('Pro', 'Profesor'), ('Tec', 'Tecnico')], default='Pro', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('direccion', models.TextField()),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('fechaNacimiento', models.DateField()),
                ('dui', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('acronimo', models.CharField(max_length=11)),
                ('completo', models.CharField(max_length=40)),
                ('cantidad_alumnos', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('numero', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.Alumno')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.Empleado')),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.Encargado')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.Horario'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.Empleado'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.Encargado'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.Grupo'),
        ),
    ]
