# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='acronimo',
            field=models.CharField(max_length=12),
        ),
    ]
