# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaEstado',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_metrica', models.DateField()),
                ('cantidad', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.Estado')),
            ],
        ),
    ]
