# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='db_app.Encargado'),
        ),
        migrations.AlterField(
            model_name='encargado',
            name='dui',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
