# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0002_auto_20180607_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='alumnosInscritos',
            field=models.IntegerField(default=0),
        ),
    ]
