# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0003_grupo_alumnosinscritos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'permissions': (('ver_alumno', 'Ver alumno'),)},
        ),
    ]
