# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterINFO',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=8)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField()),
            ],
        ),
    ]
